# Generated by Django 4.2.9 on 2024-02-02 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_id", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("status", models.IntegerField(default=1)),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("update_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=50)),
                ("avatar", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=50)),
                ("status", models.IntegerField(default=1)),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("update_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "member",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField()),
                ("product_id", models.IntegerField()),
                ("product_name", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("status", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "order_detail",
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_id", models.IntegerField()),
                ("member_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("money", models.FloatField()),
                ("status", models.IntegerField(default=1)),
                ("payment_status", models.IntegerField(default=1)),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("update_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField()),
                ("member_id", models.IntegerField()),
                ("money", models.FloatField()),
                ("type", models.IntegerField()),
                ("bank", models.IntegerField(default=1)),
                ("status", models.IntegerField(default=1)),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("update_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "payment",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_id", models.IntegerField()),
                ("category_id", models.IntegerField()),
                ("cover_pic", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                ("status", models.IntegerField(default=1)),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("update_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cover_pic", models.CharField(max_length=255)),
                ("banner_pic", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("status", models.IntegerField(default=1)),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("update_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "shop",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50)),
                ("nickname", models.CharField(max_length=50)),
                ("password_hash", models.CharField(max_length=100)),
                ("password_salt", models.CharField(max_length=50)),
                ("status", models.IntegerField(default=1)),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("update_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
