# Generated by Django 4.2.9 on 2024-02-01 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0002_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cover_pic", models.CharField(max_length=255)),
                ("banner_pic", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("status", models.IntegerField(default=1)),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("update_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "shop",
            },
        ),
    ]
