# Generated by Django 4.2.9 on 2024-02-01 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0003_shop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_id", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("status", models.IntegerField(default=1)),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("update_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=50)),
                ("avatar", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=50)),
                ("status", models.IntegerField(default=1)),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("update_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "member",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_id", models.IntegerField()),
                ("category_id", models.IntegerField()),
                ("cover_pic", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                ("status", models.IntegerField(default=1)),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("update_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "product",
            },
        ),
    ]
